spring:
  application:
    name: Api

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: health,info
  security:
    enabled: true

jwt:
  public:
    key: classpath:authz.pub
  private:
    key: classpath:authz.pem
